# Stage 1: Build the React app using Node.js
FROM node:22-alpine AS build

WORKDIR /app

# Copy dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the files
COPY . .

# Build the app
RUN npm run build

# Stage 2: Serve with NGINX
FROM nginx:1.25-alpine

# Replace default nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy build files
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
