version: '3.8' 

services:
  frontend:
    image: 370919050943.dkr.ecr.Mumbai ap-south-1.amazonaws.com/my-frontend-app:latest
    ports:
      - "80:80"
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=http://18.223.111.185:8000/api/

  backend:
    image: 370919050943.dkr.ecr.Mumbai ap-south-1.amazonaws.com/my-backend-app:latest

    ports:
      - "8000:8000"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db 
      MYSQL_PORT: 3306
      DJANGO_SECRET_KEY: "ffa*u(hkr@(*patqr@++y=_-%tc)d3xi44b)vm1m^01m8!4fha"
      DJANGO_ALLOWED_HOSTS: "*" 
      DJANGO_DEBUG: "False" 

    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_assword # Root password for MySQL
      MYSQL_DATABASE: mydatabase        # Database name to create
      MYSQL_USER: user                  # User for the database
      MYSQL_PASSWORD: password          # Password for the user
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db_data: