name: CI/CD for Full Stack App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-backend-app:latest ./backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-backend-app:latest

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend-app:latest ./frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend-app:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker stop backend || true && docker rm backend || true
          docker stop frontend || true && docker rm frontend || true

          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-backend-app:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend-app:latest

          docker run -d --name backend -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/my-backend-app:latest
          docker run -d --name frontend -p 3000:80 ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend-app:latest
